substitutions:
  _TERRAFORM_IMAGE: 'hashicorp/terraform'
  _TERRAFORM_VERSION: '0.12.26'
  _APP: 'demo'
  _ENV: 'nonprod-build'        #ENV are controlled by substitution in cloudbuild to target different environments (np/sandpit/dev01/e2e3)
  _TF_LOG: ''
#options:
    #workerPool: ${_WORKER}
tags:
  - psp-infra
  - psp-infra-terraform-plan
  - github_status_Terraform_plan_in_${PROJECT_ID}
steps:
  - id: validate
    name: ${_TERRAFORM_IMAGE}:${_TERRAFORM_VERSION}
    entrypoint: bash
    env:
      - ENV=${_ENV}
      - APP=${_TIER}
      - PROJECT_ID=${PROJECT_ID}
    args:
      - -exuo
      - pipefail
      - bin/terraform-validate.sh
  - id: plan
    name: ${_TERRAFORM_IMAGE}:${_TERRAFORM_VERSION}
    entrypoint: bash
    env:
      - ENV=${_ENV}
      - APP=${_APP}
      - BRANCH_NAME=${BRANCH_NAME}
      - TF_LOG=${_TF_LOG}
      - PROJECT_ID=${PROJECT_ID}
    args:
      - -exuo
      - pipefail
      - bin/terraform-plan.sh
timeout: 2400s
